'use strict';

var assert = require('assert');
var policy = require('./careerBackupPolicy.js');

var small = policy.exportPreflight({ physicalRecordCount: 2000, activeRecordCount: 2000 });
assert.strictEqual(small.allowed, true, 'a supported multi-player ledger remains inside the V1.2 allocation bound');
assert.strictEqual(small.physicalRecordCount, 2000);
assert.strictEqual(small.activeRecordCount, 2000);
assert.strictEqual(small.estimatedBytes, policy.FIXED_BACKUP_OVERHEAD_BYTES + 2000 * policy.REPRESENTATIVE_BYTES_PER_RECORD);
assert.strictEqual(policy.exportPreflight({ physicalRecordCount: 10000, activeRecordCount: 9900 }).allowed, false, 'the conservative multi-player estimate rejects an unbounded export allocation');
var large = policy.exportPreflight({ physicalRecordCount: 100000, activeRecordCount: 99000 });
assert.strictEqual(large.allowed, false, 'the untested hundreds-of-MiB 100k ledger is rejected before export allocation');
assert.ok(large.estimatedBytes > policy.MAX_BACKUP_BYTES);
assert.strictEqual(policy.restorePreflight(policy.MAX_BACKUP_BYTES).allowed, true, 'the exact supported restore bound is accepted');
assert.strictEqual(policy.restorePreflight(policy.MAX_BACKUP_BYTES + 1).allowed, false, 'an oversized file is rejected before read/JSON.parse');
assert.strictEqual(policy.restorePreflight(33702808).allowed, true, 'a valid legacy Backup v1 file remains restorable');
var exact = policy.serializedPreflight({ label: 'π', records: [{ player: 'José' }] });
assert.strictEqual(exact.actualSerializedBytes, Buffer.byteLength(JSON.stringify({ label: 'π', records: [{ player: 'José' }] }) + '\n'));
assert.strictEqual(exact.allowed, true);
assert.strictEqual(small.maximumPhysicalRecordCount, 4032, 'record-count preflight remains conservative despite compressed transport');
assert.strictEqual(small.limitKind, 'in-memory-ledger');
assert.strictEqual(policy.restorePreflight(policy.MAX_COMPRESSED_FILE_BYTES).allowed, true);
var error = policy.limitError('restore', policy.restorePreflight(policy.MAX_BACKUP_BYTES + 1));
assert.strictEqual(error.code, 'CAREER_BACKUP_SIZE_LIMIT');
assert.match(error.message, /compressed file size/i);
assert.match(error.message, /career database remains intact/i);
var memoryError = policy.limitError('import', policy.exportPreflight({ physicalRecordCount: small.maximumPhysicalRecordCount + 1 }));
assert.match(memoryError.message, /safely process in memory/i);
assert.doesNotMatch(memoryError.message, /compressed file/i);
console.log('Career Backup v1 export estimate and restore file-size preflight regressions passed.');
