'use strict';

var assert = require('assert');
var fs = require('fs');
var path = require('path');

var extensionRoot = __dirname;
var manifestPath = path.join(extensionRoot, 'manifest.json');
assert.ok(fs.existsSync(manifestPath), 'production manifest exists at the unpacked-extension root');
var manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
assert.ok(manifest.permissions.includes('unlimitedStorage'), 'long-lived immutable career history receives Chrome local-storage quota exemption');
var rootNames = new Set(fs.readdirSync(extensionRoot));

function exactRootFile(relativePath) {
  assert.strictEqual(path.dirname(relativePath), '.', 'content-script dependency must be declared relative to the extension root: ' + relativePath);
  assert.ok(rootNames.has(relativePath), 'manifest filename and capitalization must exactly match a root file: ' + relativePath);
  assert.ok(fs.statSync(path.join(extensionRoot, relativePath)).isFile(), 'manifest dependency is a physical file: ' + relativePath);
}

manifest.content_scripts.forEach(function (entry) { entry.js.forEach(exactRootFile); });
exactRootFile(manifest.background.service_worker);
assert.strictEqual(manifest.background.service_worker, 'careerServiceWorker.js', 'MV3 service worker owns extension-origin career IndexedDB');
var contentEntries = manifest.content_scripts.filter(function (entry) { return entry.js.includes('content.js'); });
assert.strictEqual(contentEntries.length, 1, 'exactly one manifest entry injects content.js');
var isolated = contentEntries[0];
assert.ok(!isolated.world || isolated.world === 'ISOLATED', 'content.js runs in the isolated world');
assert.strictEqual(isolated.js[0], 'runtimeScope.js', 'runtimeScope.js is first in the same isolated-world js array');
assert.ok(isolated.js.indexOf('runtimeScope.js') < isolated.js.indexOf('content.js'));
assert.deepStrictEqual(isolated.matches, ['https://pokernow.com/games/*', 'https://www.pokernow.com/games/*']);

var main = manifest.content_scripts.find(function (entry) { return entry.world === 'MAIN'; });
assert.ok(main, 'MAIN-world WebSocket entry exists explicitly');
assert.strictEqual(main.js[0], 'runtimeScope.js', 'MAIN world receives its own runtime scope before the hook');
assert.ok(main.js.includes('websocketHook.js'));
assert.strictEqual(main.js.includes('semanticHandLedger.js'), false, 'semantic ledger is isolated-world only and does not add a competing MAIN-world parser');
assert.strictEqual(main.js.includes('preflopOpportunityReducer.js'), false, 'shadow opportunity reducer is isolated-world only and does not add a competing parser');
assert.strictEqual(main.js.includes('flopCBetOpportunityReducer.js'), false, 'shadow flop CBet reducer is isolated-world only and does not add a competing parser');
assert.strictEqual(main.js.includes('showdownStatsReducer.js'), false, 'shadow showdown reducer is isolated-world only and does not add a competing parser');
assert.strictEqual(main.js.includes('careerStatsAggregator.js'), false, 'career aggregation remains isolated from the host page');
assert.strictEqual(main.js.includes('careerContributionStore.js'), false, 'career storage remains isolated from the host page');
assert.strictEqual(main.js.includes('statExplanation.js'), false, 'read-only statistic explanations remain isolated-world only');
assert.strictEqual(main.js.includes('handStatInspector.js'), false, 'the Hand Stat Inspector remains isolated-world only');
assert.strictEqual(main.js.includes('playerProfileClassifier.js'), false, 'profile classifier is isolated-world only');
assert.strictEqual(main.js.includes('playerProfilePresentation.js'), false, 'profile presentation policy is isolated-world only');
assert.strictEqual(main.js.includes('playerProfileExplanation.js'), false, 'profile explanation adapter is isolated-world only');
assert.strictEqual(main.js.includes('playerProfileShadowStore.js'), false, 'profile shadow store is isolated-world only');
assert.strictEqual(main.js.includes('playerProfileCalibration.js'), false, 'profile calibration access remains isolated from the host page');
assert.strictEqual(main.js[1], 'showdownDiagnosticExporter.js', 'MAIN world exposes the bounded page-console showdown exporter immediately after runtime scope');
assert.strictEqual(main.js[2], 'pauseDiagnosticCaptureMain.js', 'MAIN world loads its dedicated pause diagnostic registration before the hook');
assert.strictEqual(main.js[3], 'boardCompanionDiagnosticBridge.js', 'MAIN world installs the read-only BoardCompanion DevTools bridge before the transport hook');
assert.ok(rootNames.has('boardCompanionDiagnosticBridge.js'), 'BoardCompanion bridge filename and capitalization exactly match disk');
assert.strictEqual(isolated.js[1], 'showdownDiagnosticExporter.js', 'isolated world registers the bounded showdown collector immediately after runtime scope');
assert.strictEqual(isolated.js[2], 'pauseDiagnosticCapture.js', 'isolated world registers pause diagnostics before production consumers');
assert.strictEqual(main.js.filter(function (file) { return file === 'showdownDiagnosticExporter.js'; }).length, 1, 'MAIN world packages the exact showdown exporter once');
assert.strictEqual(isolated.js.filter(function (file) { return file === 'showdownDiagnosticExporter.js'; }).length, 1, 'isolated world packages the exact showdown collector once');
assert.ok(rootNames.has('showdownDiagnosticExporter.js'), 'showdown diagnostic exporter filename and capitalization exactly match disk');
assert.ok(isolated.js.indexOf('pauseDiagnosticCapture.js') < isolated.js.indexOf('content.js'));
assert.strictEqual(isolated.js.filter(function (file) { return file === 'semanticHandLedger.js'; }).length, 1, 'semanticHandLedger.js is packaged exactly once with exact capitalization');
assert.strictEqual(rootNames.has('semanticHandLedger.js'), true, 'semanticHandLedger.js exact filename and capitalization match disk');
var semanticLedgerIndex = isolated.js.indexOf('semanticHandLedger.js');
assert.strictEqual(isolated.js[semanticLedgerIndex - 1], 'positionResolver.js', 'the semantic ledger follows the canonical position resolver');
assert.strictEqual(isolated.js[isolated.js.indexOf('positionResolver.js') - 1], 'handFinalization.js', 'the canonical resolver follows hand finalization');
assert.strictEqual(isolated.js[semanticLedgerIndex + 1], 'preflopOpportunityReducer.js', 'the shadow opportunity reducer immediately consumes the finalized ledger contract');
var reducerIndex = isolated.js.indexOf('preflopOpportunityReducer.js');
assert.strictEqual(isolated.js.filter(function (file) { return file === 'preflopOpportunityReducer.js'; }).length, 1, 'preflopOpportunityReducer.js is packaged exactly once with exact capitalization');
assert.strictEqual(rootNames.has('preflopOpportunityReducer.js'), true, 'preflopOpportunityReducer.js exact filename and capitalization match disk');
assert.strictEqual(isolated.js[reducerIndex + 1], 'flopCBetOpportunityReducer.js', 'the flop CBet reducer consumes the same finalized semantic contract after the preflop reducer');
var flopReducerIndex = isolated.js.indexOf('flopCBetOpportunityReducer.js');
assert.strictEqual(isolated.js.filter(function (file) { return file === 'flopCBetOpportunityReducer.js'; }).length, 1, 'flopCBetOpportunityReducer.js is packaged exactly once with exact capitalization');
assert.strictEqual(rootNames.has('flopCBetOpportunityReducer.js'), true, 'flopCBetOpportunityReducer.js exact filename and capitalization match disk');
assert.strictEqual(isolated.js[flopReducerIndex + 1], 'showdownStatsReducer.js', 'the showdown reducer consumes finalized semantic records after the flop reducer');
var showdownReducerIndex = isolated.js.indexOf('showdownStatsReducer.js');
assert.strictEqual(isolated.js.filter(function (file) { return file === 'showdownStatsReducer.js'; }).length, 1, 'showdownStatsReducer.js is packaged exactly once with exact capitalization');
assert.strictEqual(rootNames.has('showdownStatsReducer.js'), true, 'showdownStatsReducer.js exact filename and capitalization match disk');
var statExplanationIndex = isolated.js.indexOf('statExplanation.js');
var careerAggregatorIndex = isolated.js.indexOf('careerStatsAggregator.js');
var filteredStatsIndex = isolated.js.indexOf('filteredStats.js');
var sessionStatsCacheIndex = isolated.js.indexOf('sessionStatsCache.js');
var sessionRuntimeIndex = isolated.js.indexOf('sessionRuntime.js');
var runtimeBoundsIndex = isolated.js.indexOf('runtimeBounds.js');
var careerStoreIndex = isolated.js.indexOf('careerContributionStore.js');
var careerIndexedStoreIndex = isolated.js.indexOf('careerIndexedStore.js');
var careerBackupPolicyIndex = isolated.js.indexOf('careerBackupPolicy.js');
var careerDataSettingsIndex = isolated.js.indexOf('careerDataSettings.js');
assert.strictEqual(isolated.js[showdownReducerIndex + 1], 'careerStatsAggregator.js', 'career aggregation loads after every certified statistic reducer');
assert.strictEqual(isolated.js[careerAggregatorIndex + 1], 'filteredStats.js', 'filtered aggregation loads after its exact-counter dependency');
assert.strictEqual(isolated.js[filteredStatsIndex + 1], 'sessionStatsCache.js', 'the shared Session-stat cache loads after its exact filter dependency');
assert.strictEqual(isolated.js[sessionStatsCacheIndex + 1], 'sessionRuntime.js', 'revision and persistence planning load after the shared cache');
assert.strictEqual(isolated.js[sessionRuntimeIndex + 1], 'runtimeBounds.js', 'bounded runtime collections load after Session runtime policy');
assert.strictEqual(isolated.js[runtimeBoundsIndex + 1], 'careerContributionStore.js', 'the immutable career store follows the performance-runtime contracts');
assert.strictEqual(isolated.js[careerStoreIndex + 1], 'careerIndexedStore.js', 'the indexed career backend loads after the Phase 1 migration reader');
assert.strictEqual(isolated.js[careerIndexedStoreIndex + 1], 'careerBackupPolicy.js', 'Career Backup size policy follows the career service proxy');
assert.strictEqual(isolated.js[careerBackupPolicyIndex + 1], 'careerDataSettings.js', 'Career Data presentation follows the shared backup policy');
assert.strictEqual(isolated.js[careerDataSettingsIndex + 1], 'statExplanation.js', 'stat explanations follow the additive career UI presenter');
assert.strictEqual(isolated.js.filter(function (file) { return file === 'careerStatsAggregator.js'; }).length, 1, 'careerStatsAggregator.js is packaged exactly once');
assert.strictEqual(isolated.js.filter(function (file) { return file === 'positionResolver.js'; }).length, 1, 'positionResolver.js is packaged exactly once');
assert.strictEqual(isolated.js.filter(function (file) { return file === 'filteredStats.js'; }).length, 1, 'filteredStats.js is packaged exactly once');
assert.strictEqual(isolated.js.filter(function (file) { return file === 'sessionStatsCache.js'; }).length, 1, 'sessionStatsCache.js is packaged exactly once');
assert.strictEqual(isolated.js.filter(function (file) { return file === 'sessionRuntime.js'; }).length, 1, 'sessionRuntime.js is packaged exactly once');
assert.strictEqual(isolated.js.filter(function (file) { return file === 'runtimeBounds.js'; }).length, 1, 'runtimeBounds.js is packaged exactly once');
assert.strictEqual(isolated.js.filter(function (file) { return file === 'careerContributionStore.js'; }).length, 1, 'careerContributionStore.js is packaged exactly once');
assert.strictEqual(isolated.js.filter(function (file) { return file === 'careerIndexedStore.js'; }).length, 1, 'careerIndexedStore.js is packaged exactly once');
assert.strictEqual(isolated.js.filter(function (file) { return file === 'careerBackupPolicy.js'; }).length, 1, 'careerBackupPolicy.js is packaged exactly once');
assert.strictEqual(isolated.js.filter(function (file) { return file === 'careerDataSettings.js'; }).length, 1, 'careerDataSettings.js is packaged exactly once');
assert.ok(rootNames.has('careerStatsAggregator.js') && rootNames.has('careerContributionStore.js') && rootNames.has('careerIndexedStore.js') && rootNames.has('careerBackupPolicy.js'), 'career module filenames and capitalization exactly match disk');
assert.ok(rootNames.has('sessionStatsCache.js') && rootNames.has('sessionRuntime.js') && rootNames.has('runtimeBounds.js'), 'performance runtime module filenames and capitalization exactly match disk');
assert.ok(fs.readFileSync('content.js', 'utf8').includes("['PokerSessionStatsCache', globalThis.PokerSessionStatsCache, 'sessionStatsCache.js']"), 'startup validation requires the shared Session-stat cache global');
assert.ok(fs.readFileSync('content.js', 'utf8').includes("['PokerSessionRuntime', globalThis.PokerSessionRuntime, 'sessionRuntime.js']"), 'startup validation requires revision/persistence policy');
assert.ok(fs.readFileSync('content.js', 'utf8').includes("['PokerRuntimeBounds', globalThis.PokerRuntimeBounds, 'runtimeBounds.js']"), 'startup validation requires bounded runtime collections');
assert.ok(fs.readFileSync('content.js', 'utf8').includes("['PokerCareerIndexedStore', globalThis.PokerCareerIndexedStore, 'careerIndexedStore.js']"), 'startup validation requires the exact indexed career backend global');
assert.ok(fs.readFileSync('content.js', 'utf8').includes("['PokerCareerBackupPolicy', globalThis.PokerCareerBackupPolicy, 'careerBackupPolicy.js']"), 'startup validation requires the shared backup policy global');
assert.ok(fs.readFileSync('content.js', 'utf8').includes("['PokerCareerDataSettings', globalThis.PokerCareerDataSettings, 'careerDataSettings.js']"), 'startup validation requires the Career Data presentation global');
assert.strictEqual(isolated.js.filter(function (file) { return file === 'statExplanation.js'; }).length, 1, 'statExplanation.js is packaged exactly once');
assert.strictEqual(rootNames.has('statExplanation.js'), true, 'statExplanation.js exact filename and capitalization match disk');
var handStatInspectorIndex = isolated.js.indexOf('handStatInspector.js');
assert.strictEqual(isolated.js[statExplanationIndex + 1], 'handStatInspector.js', 'the inspector consumes read-only explanations immediately after their module');
assert.strictEqual(isolated.js.filter(function (file) { return file === 'handStatInspector.js'; }).length, 1, 'handStatInspector.js is packaged exactly once');
assert.strictEqual(rootNames.has('handStatInspector.js'), true, 'handStatInspector.js exact filename and capitalization match disk');
var profileScoreInspectorIndex = isolated.js.indexOf('playerProfileScoreInspector.js');
var profileClassifierIndex = isolated.js.indexOf('playerProfileClassifier.js');
var profilePresentationIndex = isolated.js.indexOf('playerProfilePresentation.js');
var profileExplanationIndex = isolated.js.indexOf('playerProfileExplanation.js');
var profileStoreIndex = isolated.js.indexOf('playerProfileShadowStore.js');
var profileCalibrationIndex = isolated.js.indexOf('playerProfileCalibration.js');
var playerNotesIndex = isolated.js.indexOf('playerNotesStore.js');
var playerDashboardIndex = isolated.js.indexOf('playerDashboard.js');
assert.strictEqual(isolated.js[handStatInspectorIndex + 1], 'playerProfileScoreInspector.js', 'profile score inspector follows the existing read-only Hand Stat Inspector');
assert.strictEqual(isolated.js[profileScoreInspectorIndex + 1], 'playerProfileClassifier.js', 'classifier and profile runtime modules follow the standalone diagnostics presenter');
assert.strictEqual(isolated.js[profileClassifierIndex + 1], 'playerProfilePresentation.js', 'presentation policy loads after its raw classifier dependency');
assert.strictEqual(isolated.js[profilePresentationIndex + 1], 'playerProfileExplanation.js', 'explanation adapter loads after its authoritative classifier and presentation dependencies');
assert.strictEqual(isolated.js[profileExplanationIndex + 1], 'playerProfileShadowStore.js', 'shadow store loads after its classifier, presentation, and explanation dependencies');
assert.strictEqual(isolated.js[profileStoreIndex + 1], 'playerProfileCalibration.js', 'read-only calibration helper follows its shadow-store dependency');
assert.strictEqual(isolated.js[profileCalibrationIndex + 1], 'playerNotesStore.js', 'mutable notes follow profile calibration without entering profile state');
assert.strictEqual(isolated.js[playerNotesIndex + 1], 'playerDashboard.js', 'dashboard presentation follows its stable-ID notes dependency');
assert.strictEqual(isolated.js[playerDashboardIndex + 1], 'overlayStats.js', 'exact production order resumes existing HUD modules after the dashboard');
assert.strictEqual(isolated.js.filter(function (file) { return file === 'playerProfileClassifier.js'; }).length, 1, 'classifier is packaged once with exact capitalization');
assert.strictEqual(isolated.js.filter(function (file) { return file === 'playerProfileScoreInspector.js'; }).length, 1, 'profile score inspector is packaged once with exact capitalization');
assert.strictEqual(isolated.js.filter(function (file) { return file === 'playerProfilePresentation.js'; }).length, 1, 'presentation policy is packaged once with exact capitalization');
assert.strictEqual(isolated.js.filter(function (file) { return file === 'playerProfileExplanation.js'; }).length, 1, 'profile explanation adapter is packaged once with exact capitalization');
assert.strictEqual(isolated.js.filter(function (file) { return file === 'playerProfileShadowStore.js'; }).length, 1, 'profile store is packaged once with exact capitalization');
assert.strictEqual(isolated.js.filter(function (file) { return file === 'playerProfileCalibration.js'; }).length, 1, 'calibration helper is packaged once with exact capitalization');
assert.ok(rootNames.has('playerProfileScoreInspector.js') && rootNames.has('playerProfileClassifier.js') && rootNames.has('playerProfilePresentation.js') && rootNames.has('playerProfileExplanation.js') && rootNames.has('playerProfileShadowStore.js') && rootNames.has('playerProfileCalibration.js'), 'profile diagnostics/runtime filenames and capitalization exactly match disk');
assert.ok(semanticLedgerIndex < reducerIndex && reducerIndex < flopReducerIndex && flopReducerIndex < showdownReducerIndex && showdownReducerIndex < careerAggregatorIndex && careerAggregatorIndex < careerStoreIndex && careerStoreIndex < statExplanationIndex && statExplanationIndex < handStatInspectorIndex && handStatInspectorIndex < profileScoreInspectorIndex && profileScoreInspectorIndex < profileClassifierIndex && profileClassifierIndex < profilePresentationIndex && profilePresentationIndex < profileExplanationIndex && profileExplanationIndex < profileStoreIndex && profileStoreIndex < profileCalibrationIndex && profileCalibrationIndex < isolated.js.indexOf('content.js'), 'ledger, reducers, career consumer, explanation consumers, diagnostics, and all profile modules register before content.js dependency validation');
assert.ok(rootNames.has('pauseDiagnosticCapture.js') && rootNames.has('pauseDiagnosticCaptureMain.js'), 'world-specific diagnostic filenames and capitalization match disk');
assert.strictEqual(fs.readFileSync(path.join(extensionRoot, 'pauseDiagnosticCaptureMain.js'), 'utf8'), fs.readFileSync(path.join(extensionRoot, 'pauseDiagnosticCapture.js'), 'utf8'), 'world-specific capture engines remain byte-identical');
assert.ok(!JSON.stringify(manifest).includes('runtimeGuard.js'), 'deleted runtimeGuard.js is absent from the production manifest');
assert.strictEqual(fs.existsSync(path.join(extensionRoot, 'runtimeGuard.js')), false, 'deleted helper is absent from the production root');

var buildPattern = /(?:v\d+\.\d+\.\d+-public-\d{8}|v\d+\.\d+\.\d+-rc\d+-\d{8}-\d{4}|[a-z][a-z0-9-]+-\d{8}-\d{4})/;
var runtimeSource = fs.readFileSync(path.join(extensionRoot, 'runtimeScope.js'), 'utf8');
var contentSource = fs.readFileSync(path.join(extensionRoot, 'content.js'), 'utf8');
var popupSource = fs.readFileSync(path.join(extensionRoot, 'popup.js'), 'utf8');
var careerWorkerSource = fs.readFileSync(path.join(extensionRoot, 'careerServiceWorker.js'), 'utf8');
var careerBackupSource = fs.readFileSync(path.join(extensionRoot, 'careerBackup.js'), 'utf8');
var ledgerSource = fs.readFileSync(path.join(extensionRoot, 'semanticHandLedger.js'), 'utf8');
var reducerSource = fs.readFileSync(path.join(extensionRoot, 'preflopOpportunityReducer.js'), 'utf8');
var flopReducerSource = fs.readFileSync(path.join(extensionRoot, 'flopCBetOpportunityReducer.js'), 'utf8');
var showdownReducerSource = fs.readFileSync(path.join(extensionRoot, 'showdownStatsReducer.js'), 'utf8');
var statExplanationSource = fs.readFileSync(path.join(extensionRoot, 'statExplanation.js'), 'utf8');
var handStatInspectorSource = fs.readFileSync(path.join(extensionRoot, 'handStatInspector.js'), 'utf8');
var profileScoreInspectorSource = fs.readFileSync(path.join(extensionRoot, 'playerProfileScoreInspector.js'), 'utf8');
var profileClassifierSource = fs.readFileSync(path.join(extensionRoot, 'playerProfileClassifier.js'), 'utf8');
var profilePresentationSource = fs.readFileSync(path.join(extensionRoot, 'playerProfilePresentation.js'), 'utf8');
var profileExplanationSource = fs.readFileSync(path.join(extensionRoot, 'playerProfileExplanation.js'), 'utf8');
var profileStoreSource = fs.readFileSync(path.join(extensionRoot, 'playerProfileShadowStore.js'), 'utf8');
var profileCalibrationSource = fs.readFileSync(path.join(extensionRoot, 'playerProfileCalibration.js'), 'utf8');
var showdownExporterSource = fs.readFileSync(path.join(extensionRoot, 'showdownDiagnosticExporter.js'), 'utf8');
var buildIds = [runtimeSource, contentSource, popupSource, careerWorkerSource].map(function (source) {
  var match = source.match(buildPattern);
  assert.ok(match, 'runtimeScope, content, popup, and career service worker each embed a build ID');
  return match[0];
});
assert.strictEqual(new Set(buildIds).size, 1, 'runtimeScope, content, popup, and career service worker build IDs match');
assert.ok(careerWorkerSource.includes("importScripts('stats.js', 'careerStatsAggregator.js', 'filteredStats.js', 'careerContributionStore.js', 'careerIndexedStore.js', 'careerBackupPolicy.js', 'careerBackup.js')"), 'career service worker loads the exact filtered persistence, size-policy, and formal-backup dependency chain');
assert.ok(careerWorkerSource.includes('PokerCareerIndexedStore.createIndexedService(indexedDB'), 'career service worker opens IndexedDB in the extension origin');
assert.ok(rootNames.has('careerBackup.js') && careerBackupSource.includes('root.PokerCareerBackup = api;'), 'canonical career backup validator is packaged exactly once at the extension root');
assert.ok(careerWorkerSource.includes('PokerCareerBackup.validateBackup') && careerWorkerSource.includes('replaceCareerRecords'), 'service worker validates before atomic replacement');
assert.strictEqual(/\bindexedDB\b/.test(contentSource), false, 'content script never accesses host-page IndexedDB');
assert.ok(contentSource.includes('PokerCareerIndexedStore.createMessageService(chrome.runtime)'), 'content script uses the dedicated career service-worker proxy');
assert.ok(runtimeSource.includes('[HUD RUNTIME SCOPE] helper installed'));
assert.ok(runtimeSource.indexOf('[HUD BUILD] runtimeScope') < runtimeSource.indexOf('[HUD RUNTIME SCOPE] helper installed'));
assert.ok(fs.readFileSync(path.join(extensionRoot, manifest.action.default_popup), 'utf8').includes('pnhud-popup-build-id'), 'popup visibly exposes the build ID');
assert.ok(ledgerSource.includes('root.PokerSemanticHandLedger = api;'), 'semantic ledger registers the exact required production global');
assert.ok(contentSource.includes("['PokerSemanticHandLedger', globalThis.PokerSemanticHandLedger, 'semanticHandLedger.js']"), 'stage 1.4 retains the semantic ledger as a required module');
assert.ok(reducerSource.includes('root.PokerPreflopOpportunityReducer = api;'), 'shadow opportunity reducer registers the exact required production global');
assert.ok(flopReducerSource.includes('root.PokerFlopCBetOpportunityReducer = api;'), 'shadow flop CBet reducer registers the exact required production global');
assert.ok(contentSource.includes('PokerFlopCBetOpportunityReducer') && contentSource.includes('flopCBetOpportunityReducer.js'), 'stage 1.4 requires the shadow flop CBet reducer');
assert.ok(showdownReducerSource.includes('root.PokerShowdownStatsReducer = api;'), 'shadow showdown reducer registers the exact required production global');
assert.ok(statExplanationSource.includes('root.PokerHandStatExplanation = api;'), 'stat explanation module registers its isolated-world global');
assert.ok(contentSource.includes("['PokerHandStatExplanation', globalThis.PokerHandStatExplanation, 'statExplanation.js']"), 'stage 1.4 requires stat explanations before content initialization');
assert.ok(handStatInspectorSource.includes('root.PokerHandStatInspector = api;'), 'Hand Stat Inspector registers its isolated-world presentation global');
assert.ok(contentSource.includes("['PokerHandStatInspector', globalThis.PokerHandStatInspector, 'handStatInspector.js']"), 'stage 1.4 requires the inspector before content initialization');
assert.ok(profileScoreInspectorSource.includes('root.PokerPlayerProfileScoreInspector = api;'), 'profile score inspector registers its isolated-world presentation global');
assert.ok(contentSource.includes("['PokerPlayerProfileScoreInspector', globalThis.PokerPlayerProfileScoreInspector, 'playerProfileScoreInspector.js']"), 'stage 1.4 requires profile score diagnostics before content initialization');
assert.ok(showdownExporterSource.includes('root.PokerNowHUDDebug = pageApi;'), 'packaged exporter registers the exact page-console global');
assert.ok(showdownExporterSource.includes('exportShowdownDiagnostics') && showdownExporterSource.includes('latestShowdownDiagnostic') && showdownExporterSource.includes('clearShowdownDiagnostics'), 'packaged exporter contains all three read/clear console methods');
assert.ok(contentSource.includes("['PokerShowdownStatsReducer', globalThis.PokerShowdownStatsReducer, 'showdownStatsReducer.js']"), 'stage 1.4 requires the shadow showdown reducer');
assert.ok(profileClassifierSource.includes('root.PokerPlayerProfileClassifier = api;'), 'classifier registers its exact production global');
assert.ok(profileClassifierSource.includes('scoreDecomposition: scoreDecomposition'), 'packaged classifier retains read-only semantic score decomposition');
assert.ok(profileClassifierSource.includes('featureDiagnostics: Object.keys(features).reduce'), 'packaged decomposition retains diagnostic data availability separately from scoring support');
assert.ok(profilePresentationSource.includes('root.PokerPlayerProfilePresentation = api;'), 'presentation policy registers its exact production global');
assert.ok(profileExplanationSource.includes('root.PokerPlayerProfileExplanation = api;'), 'profile explanation adapter registers its exact production global');
assert.ok(profileStoreSource.includes('root.PokerPlayerProfileShadowStore = api;'), 'profile store registers its exact production global');
assert.ok(profileCalibrationSource.includes('root.PokerPlayerProfileCalibration = api;'), 'profile calibration helper registers its exact production global');
assert.ok(contentSource.includes("['PokerPlayerProfileClassifier', globalThis.PokerPlayerProfileClassifier, 'playerProfileClassifier.js']"), 'stage 1.4 requires the classifier');
assert.ok(contentSource.includes("['PokerPlayerProfilePresentation', globalThis.PokerPlayerProfilePresentation, 'playerProfilePresentation.js']"), 'stage 1.4 requires the presentation policy');
assert.ok(contentSource.includes("['PokerPlayerProfileExplanation', globalThis.PokerPlayerProfileExplanation, 'playerProfileExplanation.js']"), 'stage 1.4 requires profile explanations');
assert.ok(contentSource.includes("['PokerPlayerProfileShadowStore', globalThis.PokerPlayerProfileShadowStore, 'playerProfileShadowStore.js']"), 'stage 1.4 requires the profile store');
assert.ok(contentSource.includes("['PokerPlayerProfileCalibration', globalThis.PokerPlayerProfileCalibration, 'playerProfileCalibration.js']"), 'stage 1.4 requires the calibration helper');
assert.ok(contentSource.includes('installPlayerProfileDebugApi(playerProfileDebugApi)'), 'content explicitly exposes the isolated-world debug API across console global aliases');
assert.ok(contentSource.includes('explainPlayerProfile: explainPlayerProfile'), 'profile debug API exposes JSON-safe player explanations');
assert.strictEqual(JSON.stringify(manifest).includes('playerProfileDebugBridge.js'), false, 'profile data is never bridged into the host page world');
assert.ok(contentSource.includes("['PokerPreflopOpportunityReducer', globalThis.PokerPreflopOpportunityReducer, 'preflopOpportunityReducer.js']"), 'stage 1.4 requires the shadow opportunity reducer');
assert.ok(!JSON.stringify(manifest).includes('testSupport') && !JSON.stringify(manifest).includes('rawFixtureFactExtractor'), 'test-only prototype utilities are not packaged');
assert.ok(!JSON.stringify(manifest).includes('capture-derived-preflop') && !JSON.stringify(manifest).includes('captureDerivedPreflopProductionReplay'), 'sanitized capture-derived fixture assets and replay utilities remain test-only');
assert.strictEqual(JSON.stringify(manifest).toLowerCase().includes('.har'), false, 'raw HAR captures are never packaged');

console.log('Production extension package validated at ' + extensionRoot + ' · build ' + buildIds[0]);
