'use strict';
var assert = require('assert');
var potOdds = require('./potOdds.js');

function input(overrides) {
  return Object.assign({
    enabled: true, localPlayerId: 'hero', actingPlayerId: 'hero', handId: 'h1', street: 'flop',
    players: [
      { playerId: 'hero', streetContribution: 0, totalContribution: 5, stack: 100, active: true },
      { playerId: 'villain', streetContribution: 5, totalContribution: 10, stack: 100, active: true }
    ]
  }, overrides || {});
}
function supported(overrides) { var result = potOdds.resolve(input(overrides)); assert.strictEqual(result.status, 'supported'); return result; }

var freeCheck = potOdds.resolve(input({ players: input().players.map(function (p) { return Object.assign({}, p, { streetContribution: 0 }); }) }));
assert.strictEqual(freeCheck.status, 'supported'); assert.strictEqual(freeCheck.reasonCode, 'NO_CALL_REQUIRED'); assert.strictEqual(freeCheck.amountToCall, 0); assert.strictEqual(freeCheck.requiredEquity, null);
assert.ok(potOdds.widgetHtml(freeCheck).includes('Call 0 · Need —'), 'supported free check stays visible without a manufactured percentage or currency symbol');
var unavailableFreeState = potOdds.resolve(input({ actingPlayerId: null, players: input().players.map(function (p) { return Object.assign({}, p, { streetContribution: 0 }); }) }));
assert.strictEqual(unavailableFreeState.status, 'unsupported'); assert.strictEqual(unavailableFreeState.reasonCode, 'MISSING_ACTION_STATE'); assert.strictEqual(potOdds.widgetHtml(unavailableFreeState), '', 'unknown state remains fail closed instead of becoming a free-check panel');
var normal = supported(); assert.strictEqual(normal.amountToCall, 5); assert.strictEqual(normal.currentEligiblePot, 15); assert.strictEqual(normal.requiredEquity, 0.25); assert.strictEqual(potOdds.formatPercent(normal.requiredEquity), '25.0%');
var blind = supported({ street: 'preflop', players: [{ playerId: 'hero', streetContribution: 0.5, totalContribution: 0.5, stack: 99.5 }, { playerId: 'villain', streetContribution: 2, totalContribution: 2, stack: 98 }] }); assert.strictEqual(blind.amountToCall, 1.5, 'posted BB/SB contribution is subtracted');
var bbOpen = supported({ street: 'preflop', currentPot: 0, players: [{ playerId: 'hero', streetContribution: 20, totalContribution: null, stack: 980 }, { playerId: 'sb', streetContribution: 10, totalContribution: null, stack: 990 }, { playerId: 'opener', streetContribution: 60, totalContribution: null, stack: 940 }] });
assert.strictEqual(bbOpen.currentEligiblePot, 90); assert.strictEqual(bbOpen.amountToCall, 40); assert.strictEqual(bbOpen.potAfterCall, 130); assert.strictEqual(potOdds.formatPercent(bbOpen.requiredEquity), '30.8%'); assert.strictEqual(bbOpen.evidence.namedPot, 0); assert.strictEqual(bbOpen.evidence.commitmentPot, 90); assert.strictEqual(bbOpen.evidence.commitmentFloorApplied, true); assert.deepStrictEqual(bbOpen.evidence.streetCommitmentPlayerIds, ['hero', 'sb', 'opener']);
var sbOpen = supported({ street: 'preflop', currentPot: 0, players: [{ playerId: 'hero', streetContribution: 10, totalContribution: null, stack: 990 }, { playerId: 'bb', streetContribution: 20, totalContribution: null, stack: 980 }, { playerId: 'opener', streetContribution: 60, totalContribution: null, stack: 940 }] });
assert.strictEqual(sbOpen.currentEligiblePot, 90); assert.strictEqual(sbOpen.amountToCall, 50); assert.strictEqual(sbOpen.potAfterCall, 140); assert.strictEqual(potOdds.formatPercent(sbOpen.requiredEquity), '35.7%');
var preflopDeadMoney = supported({ street: 'preflop', currentPot: 0, players: [{ playerId: 'hero', streetContribution: 20, totalContribution: null, stack: 980 }, { playerId: 'sb', streetContribution: 10, totalContribution: null, stack: 990, folded: true }, { playerId: 'opener', streetContribution: 60, totalContribution: null, stack: 940 }, { playerId: 'caller', streetContribution: 60, totalContribution: null, stack: 940 }, { playerId: 'folded-limper', streetContribution: 20, totalContribution: null, stack: 980, folded: true }] });
assert.strictEqual(preflopDeadMoney.currentEligiblePot, 170, 'callers and folded preflop dead money remain in the eligible pot'); assert.strictEqual(preflopDeadMoney.amountToCall, 40); assert.strictEqual(preflopDeadMoney.potAfterCall, 210);
var straddleLike = supported({ street: 'preflop', currentPot: 0, players: [{ playerId: 'hero', streetContribution: 20, totalContribution: null, stack: 980 }, { playerId: 'sb', streetContribution: 10, totalContribution: null, stack: 990 }, { playerId: 'straddle', streetContribution: 40, totalContribution: null, stack: 960 }] });
assert.strictEqual(straddleLike.currentEligiblePot, 70); assert.strictEqual(straddleLike.amountToCall, 20, 'supported live straddle-equivalent commitment prices the call');
var namedPotFloor = supported({ street: 'preflop', currentPot: 100, players: [{ playerId: 'hero', streetContribution: 20, totalContribution: null, stack: 980 }, { playerId: 'sb', streetContribution: 10, totalContribution: null, stack: 990 }, { playerId: 'opener', streetContribution: 60, totalContribution: null, stack: 940 }] });
assert.strictEqual(namedPotFloor.currentEligiblePot, 100, 'a larger authoritative named pot is not double-counted with preflop commitments'); assert.strictEqual(namedPotFloor.evidence.commitmentFloorApplied, false);
assert.strictEqual(supported({ players: [{ playerId: 'hero', streetContribution: 5, totalContribution: 15, stack: 95 }, { playerId: 'villain', streetContribution: 20, totalContribution: 25, stack: 80 }] }).amountToCall, 15, 'raise-to amount is not the incremental call');
assert.strictEqual(supported({ street: 'preflop', players: [{ playerId: 'hero', streetContribution: 2, totalContribution: 2, stack: 98 }, { playerId: 'v1', streetContribution: 8, totalContribution: 8, stack: 92 }, { playerId: 'v2', streetContribution: 8, totalContribution: 8, stack: 92 }] }).amountToCall, 6, '3Bet/multiway call uses highest minus self');
assert.strictEqual(supported({ street: 'preflop', players: [{ playerId: 'hero', streetContribution: 8, totalContribution: 8, stack: 92 }, { playerId: 'v1', streetContribution: 24, totalContribution: 24, stack: 76 }] }).amountToCall, 16, '4Bet+ uses incremental amount');
var multiway = supported({ players: [{ playerId: 'hero', streetContribution: 0, totalContribution: 30, stack: 100 }, { playerId: 'v1', streetContribution: 10, totalContribution: 10, stack: 90 }, { playerId: 'v2', streetContribution: 10, totalContribution: 10, stack: 90 }] }); assert.strictEqual(multiway.currentEligiblePot, 50); assert.strictEqual(multiway.amountToCall, 10); assert.strictEqual(potOdds.formatPercent(multiway.requiredEquity), '16.7%');
var deadMoney = supported({ players: [{ playerId: 'hero', streetContribution: 0, totalContribution: 5, stack: 100 }, { playerId: 'v1', streetContribution: 5, totalContribution: 5, stack: 95 }, { playerId: 'folded', streetContribution: 2, totalContribution: 2, stack: 98, folded: true }] }); assert.strictEqual(deadMoney.currentEligiblePot, 12, 'folded-player chips remain contestable');
var namedDeadMoney = supported({ currentPot: 13, players: [{ playerId: 'hero', streetContribution: 0, totalContribution: 5, stack: 100 }, { playerId: 'v1', streetContribution: 5, totalContribution: 5, stack: 95 }, { playerId: 'folded', streetContribution: 2, totalContribution: 2, stack: 98, folded: true }] }); assert.strictEqual(namedDeadMoney.currentEligiblePot, 13, 'ordinary authoritative pot preserves dead money not represented by voluntary actions');
assert.strictEqual(potOdds.resolve(input({ actingPlayerId: 'villain' })).reasonCode, 'NOT_USERS_TURN');
assert.strictEqual(potOdds.resolve(input({ players: [Object.assign({}, input().players[0], { folded: true }), input().players[1]] })).reasonCode, 'USER_FOLDED');
assert.strictEqual(potOdds.resolve(input({ enabled: false })).reasonCode, 'DISABLED');
assert.strictEqual(potOdds.resolve(input({ transitioning: true })).reasonCode, 'HAND_TRANSITION');

var coveringJam = supported({ players: [{ playerId: 'hero', streetContribution: 0, totalContribution: 20, stack: 100 }, { playerId: 'v1', streetContribution: 50, totalContribution: 70, stack: 0, allIn: true }] }); assert.strictEqual(coveringJam.amountToCall, 50);
var liveHeadsUpJam = supported({ currentPot: 740, players: [{ playerId: 'hero', streetContribution: 0, totalContribution: null, stack: 460, active: true, inHand: true }, { playerId: 'v1', streetContribution: 460, totalContribution: 460, stack: 0, allIn: true, active: true, inHand: true }] });
assert.strictEqual(liveHeadsUpJam.amountToCall, 460); assert.strictEqual(liveHeadsUpJam.currentEligiblePot, 740); assert.strictEqual(liveHeadsUpJam.potAfterCall, 1200); assert.strictEqual(potOdds.formatPercent(liveHeadsUpJam.requiredEquity), '38.3%'); assert.strictEqual(liveHeadsUpJam.evidence.headsUpAllInProof, true);
assert.strictEqual(supported({ currentPot: 740, players: [{ playerId: 'hero', streetContribution: 0, totalContribution: null, stack: 600, active: true, inHand: true }, { playerId: 'v1', streetContribution: 460, totalContribution: null, stack: 0, allIn: true, active: true, inHand: true }] }).amountToCall, 460, 'covering a HU jam uses the all-in contribution as the price');
var shortHero = supported({ players: [{ playerId: 'hero', streetContribution: 0, totalContribution: 20, stack: 20 }, { playerId: 'v1', streetContribution: 50, totalContribution: 70, stack: 0, allIn: true }] }); assert.strictEqual(shortHero.amountToCall, 20); assert.strictEqual(shortHero.evidence.excludedExcess, 30, 'unreachable jam excess is excluded');
var shortRaise = supported({ players: [{ playerId: 'hero', streetContribution: 5, totalContribution: 15, stack: 20 }, { playerId: 'v1', streetContribution: 8, totalContribution: 18, stack: 0, allIn: true }] }); assert.strictEqual(shortRaise.amountToCall, 3, 'short non-full all-in still changes actual call amount');
assert.strictEqual(potOdds.resolve(input({ currentPot: 740, players: [{ playerId: 'hero', streetContribution: 460, totalContribution: null, stack: 460, active: true, inHand: true }, { playerId: 'v1', streetContribution: 460, totalContribution: null, stack: 0, allIn: true, active: true, inHand: true }] })).reasonCode, 'NO_CALL_REQUIRED', 'an already matched all-in has no call decision');
assert.strictEqual(potOdds.resolve(input({ currentPot: 740, players: [{ playerId: 'hero', streetContribution: 0, totalContribution: null, stack: 200, active: true, inHand: true }, { playerId: 'v1', streetContribution: 460, totalContribution: null, stack: 0, allIn: true, active: true, inHand: true }] })).reasonCode, 'AMBIGUOUS_POT_ELIGIBILITY', 'a partial-history HU undercall remains fail closed when excess eligibility cannot be proven');
assert.strictEqual(potOdds.resolve(input({ currentPot: 900, players: [{ playerId: 'hero', streetContribution: 0, totalContribution: null, stack: 460, active: true, inHand: true }, { playerId: 'v1', streetContribution: 460, totalContribution: null, stack: 0, allIn: true, active: true, inHand: true }, { playerId: 'v2', streetContribution: 460, totalContribution: null, stack: 0, active: true, inHand: true }] })).reasonCode, 'AMBIGUOUS_POT_ELIGIBILITY', 'multiway all-in does not use the narrow HU proof');
var foldedPrice = supported({ currentPot: 50, players: [{ playerId: 'hero', streetContribution: 0, totalContribution: 10, stack: 100, active: true }, { playerId: 'live', streetContribution: 20, totalContribution: 30, stack: 80, active: true }, { playerId: 'folded', streetContribution: 80, totalContribution: 80, stack: 20, folded: true, active: false }] }); assert.strictEqual(foldedPrice.amountToCall, 20, 'folded players retain dead money but do not establish the live call price');
var multiwayJamCall = supported({ currentPot: 120, players: [{ playerId: 'hero', streetContribution: 0, totalContribution: 20, stack: 100, active: true }, { playerId: 'jam', streetContribution: 40, totalContribution: 60, stack: 0, allIn: true, active: true }, { playerId: 'caller', streetContribution: 40, totalContribution: 60, stack: 100, active: true }] }); assert.strictEqual(multiwayJamCall.amountToCall, 40); assert.strictEqual(multiwayJamCall.currentEligiblePot, 140, 'complete multiway contributions retain safe cap semantics');
var sideBoth = supported({ sidePots: [{ amount: 30, resolved: true, eligiblePlayerIds: ['hero', 'v1', 'v2'] }, { amount: 20, resolved: true, eligiblePlayerIds: ['hero', 'v1'] }] }); assert.strictEqual(sideBoth.currentEligiblePot, 50);
var mainOnly = supported({ sidePots: [{ amount: 30, resolved: true, eligiblePlayerIds: ['hero', 'v1', 'v2'] }, { amount: 20, resolved: true, eligiblePlayerIds: ['v1', 'v2'] }] }); assert.strictEqual(mainOnly.currentEligiblePot, 30, 'unreachable side pot is excluded');
assert.strictEqual(potOdds.resolve(input({ sidePots: [{ amount: 30, resolved: false, eligiblePlayerIds: ['hero'] }] })).reasonCode, 'SIDE_POT_UNRESOLVED');
assert.strictEqual(potOdds.resolve(input({ players: [{ playerId: 'hero', streetContribution: 0, totalContribution: null, stack: 20 }, { playerId: 'v1', streetContribution: 50, totalContribution: null, stack: 0, allIn: true }], currentPot: 70 })).reasonCode, 'AMBIGUOUS_POT_ELIGIBILITY');
var refunded = supported({ explicitEligiblePot: 20 }); assert.strictEqual(refunded.currentEligiblePot, 20, 'resolved eligible pot wins over nominal displayed totals');

[[15,5,.25,'25.0%'],[50,10,1/6,'16.7%'],[20,20,.5,'50.0%'],[90,30,.25,'25.0%']].forEach(function (sample) {
  var result = supported({ explicitEligiblePot: sample[0], players: [{ playerId: 'hero', streetContribution: 0, totalContribution: 0, stack: sample[1] }, { playerId: 'v1', streetContribution: sample[1], totalContribution: sample[1], stack: 100 }] });
  assert.strictEqual(result.requiredEquity, sample[2]); assert.strictEqual(potOdds.formatPercent(result.requiredEquity), sample[3]);
});
var fractional = supported({ explicitEligiblePot: 1.5, players: [{ playerId: 'hero', streetContribution: 0.25, totalContribution: 0.25, stack: 5 }, { playerId: 'v1', streetContribution: 0.75, totalContribution: 1.25, stack: 5 }] }); assert.strictEqual(fractional.amountToCall, 0.5); assert.strictEqual(fractional.requiredEquity, 0.25);

var desktopPlacement = potOdds.heroPlacement({ viewport: { width: 1440, height: 900 }, size: { width: 250, height: 34 }, cardRect: { left: 672, top: 690, width: 96, height: 54 } });
assert.strictEqual(desktopPlacement.safe, true); assert.strictEqual(desktopPlacement.selectedSide, 'left'); assert.strictEqual(desktopPlacement.strategy, 'left-of-cards'); assert.deepStrictEqual(desktopPlacement.proposedRect, { left: 412, top: 700, width: 250, height: 34, right: 662, bottom: 734 }); assert.strictEqual(desktopPlacement.horizontalGap, 10); assert.strictEqual(desktopPlacement.verticalCenterDelta, 0, 'pill center aligns exactly with card center');
var call100Placement = potOdds.heroPlacement({ viewport: { width: 1024, height: 768 }, size: { width: 250, height: 30 }, cardRect: { left: 466, top: 596, width: 92, height: 56 }, obstacleRects: [{ left: 392, top: 660, width: 240, height: 24 }] });
assert.strictEqual(call100Placement.safe, true, 'CALL 100 fixture renders beside cards even when the below-card gap is crowded'); assert.strictEqual(call100Placement.selectedSide, 'left'); assert.deepStrictEqual(call100Placement.proposedRect, { left: 206, top: 609, width: 250, height: 30, right: 456, bottom: 639 }); assert.strictEqual(call100Placement.horizontalGap, 10); assert.strictEqual(call100Placement.verticalCenterDelta, 0); assert.deepStrictEqual(call100Placement.collision, { card: false, obstacleIndexes: [] });
var narrowRightPlacement = potOdds.heroPlacement({ viewport: { width: 600, height: 600 }, size: { width: 250, height: 30 }, cardRect: { left: 170, top: 430, width: 96, height: 50 } });
assert.strictEqual(narrowRightPlacement.selectedSide, 'right', 'narrow viewport falls back to the right of cards'); assert.strictEqual(narrowRightPlacement.left, 276); assert.ok(narrowRightPlacement.proposedRect.right <= 594, 'right fallback remains inside viewport'); assert.strictEqual(narrowRightPlacement.verticalCenterDelta, 0);
var selfHudBlocksLeft = potOdds.heroPlacement({ viewport: { width: 1024, height: 768 }, size: { width: 250, height: 30 }, cardRect: { left: 466, top: 596, width: 92, height: 56 }, obstacleRects: [{ left: 206, top: 590, width: 250, height: 70 }] });
assert.strictEqual(selfHudBlocksLeft.selectedSide, 'right'); assert.strictEqual(selfHudBlocksLeft.left, 568); assert.deepStrictEqual(selfHudBlocksLeft.collision, { card: false, obstacleIndexes: [] }, 'actual self HUD rectangle redirects the pill without enlarging the HUD');
var unavailableCards = potOdds.heroPlacement({ viewport: { width: 1024, height: 768 }, size: { width: 250, height: 30 } });
assert.strictEqual(unavailableCards.safe, false); assert.strictEqual(unavailableCards.suppressionReason, 'actual hero card region unavailable');
var genuinelyNoSafePlacement = potOdds.heroPlacement({ viewport: { width: 320, height: 180 }, size: { width: 308, height: 34 }, cardRect: { left: 106, top: 60, width: 108, height: 50 }, obstacleRects: [{ left: 6, top: 6, width: 308, height: 168 }] });
assert.strictEqual(genuinelyNoSafePlacement.safe, false); assert.strictEqual(genuinelyNoSafePlacement.suppressionReason, 'no bounded horizontal position beside hero cards');

assert.strictEqual(potOdds.formatAmount(10), '10'); assert.strictEqual(potOdds.formatAmount(60), '60'); assert.strictEqual(potOdds.formatAmount(188), '188'); assert.strictEqual(potOdds.formatAmount(10.5), '10.5'); assert.strictEqual(potOdds.formatAmount(10.25), '10.25');
var html = potOdds.widgetHtml(normal); assert.ok(html.includes('Call 5 · Need 25.0%')); assert.ok(html.includes('Current eligible pot: 15 chips')); assert.ok(html.includes('Call amount: 5 chips')); assert.ok(html.includes('Eligible pot after call: 20 chips')); assert.ok(html.includes('Before rake; future betting not included.')); assert.ok(!html.includes('$'), 'pot-odds UI and tooltip contain no currency symbol');
assert.strictEqual(potOdds.widgetHtml(potOdds.resolve(input({ actingPlayerId: 'villain' }))), '');
console.log('Live pot-odds ordinary, raise, multiway, all-in, eligible-pot, numeric, and fail-closed tests passed.');
