'use strict';

var categories = Object.freeze({
  protocolDecoding: [
    'parser.test.js',
    'pokernow-tb-replay.test.js',
    'tbTrace.production.integration.test.js',
    'liveActionPipeline.integration.test.js'
  ],
  actionInference: ['actionInference.test.js'],
  handLifecycle: ['lifecycleReleaseBlocker.production.test.js', 'careerRestoreFirstHand.production.test.js', 'handFinalization.test.js', 'firstHandStartup.production.test.js', 'coldStartBoundary.production.test.js', 'breakReloadRestart.production.test.js', 'finalizedAf.production.test.js', 'handLogVirtualization.production.test.js', 'interruptedHandRecovery.test.js', 'pausedLifecycleRecovery.production.test.js', 'pokerNowLifecycleSignal.production.test.js', 'ownedHandReloadContinuity.production.test.js', 'pauseRuntimeStatus.production.test.js', 'verifiedHostPauseResume.production.test.js', 'sessionPauseIdleOracle.production.test.js'],
  semanticLedger: ['semanticHandLedger.test.js', 'semanticHandLedgerFixtures.production.test.js', 'semanticHandLedgerLifecycle.production.test.js', 'semanticHandLedgerShadowNeutrality.production.test.js'],
  preflopOpportunityReducer: ['preflopOpportunityReducer.test.js', 'preflopMultiwayFoldToThreeBet.test.js', 'preflopOpportunityReducerFixtures.production.test.js', 'sanitizedCaptureDerivedPreflopFixtures.production.test.js', 'preflopHudIntegration.production.test.js', 'preflopHudContentPath.production.test.js', 'preflopOpportunityReducerLifecycle.production.test.js', 'preflopOpportunityReducerShadowNeutrality.production.test.js'],
  flopCBetOpportunityReducer: ['flopCBetOpportunityReducer.test.js', 'flopCBetStatsIntegration.production.test.js', 'flopCBetContentPath.production.test.js', 'flopCBetVisibleIntegration.production.test.js'],
  showdownStatsReducer: ['showdownStatsReducer.test.js', 'showdownUncontestedWinner.test.js', 'showdownStatsContentPath.production.test.js', 'showdownStatsAuthoritative.production.test.js', 'showdownStatsVisibleIntegration.production.test.js', 'showdownPostBreakLifecycle.production.test.js', 'showdownFirstHandLifecycle.production.test.js'],
  careerFoundation: ['careerStatsAggregator.test.js', 'careerContributionStore.test.js', 'careerStorageCapacity.test.js', 'careerProductionPath.production.test.js'],
  careerScaleAndSupersession: ['careerSupersession.test.js', 'careerIndexedStore.test.js', 'careerServiceWorker.test.js', 'careerSessionRemoval.test.js', 'careerPlayerSummaries.test.js', 'careerPlayerSummaryPerformance.test.js'],
  careerBackupDurability: ['careerBackup.test.js', 'careerBackupCorruption.test.js', 'careerBackupProductionPath.production.test.js', 'careerBackupSeparation.production.test.js', 'careerBackupPreflight.test.js', 'careerBackupPreflight.production.test.js', 'careerImport.test.js', 'careerPortableFile.test.js', 'careerDataSettings.test.js', 'careerDataSettings.production.test.js'],
  positionRelationalCrossfilter: ['positionResolver.test.js', 'positionProductionPath.production.test.js', 'positionalAggregation.test.js', 'filteredStats.test.js', 'situationalDashboard.test.js', 'selfIdentity.production.test.js'],
  careerTrends: ['careerTrends.test.js', 'careerTrendsService.test.js', 'careerTrends.production.test.js', 'careerTrendsPerformance.test.js'],
  livePotOdds: ['potOdds.test.js', 'potOddsPosition.test.js', 'potOddsDraggablePosition.production.test.js', 'boardCompanionLayout.test.js', 'boardCompanionStableTableLocal.production.test.js', 'boardCompanionDragLifecycleHardening.production.test.js', 'boardCompanionLiveUxFinalization.production.test.js', 'boardCompanionDiagnosticBridge.production.test.js', 'boardCompanionPersistentPotOdds.production.test.js', 'potOddsSemanticPath.production.test.js', 'potOddsLiveStateReconcile.production.test.js', 'potOddsDecisionRenderTrigger.production.test.js', 'potOddsProductionVisibilityHardening.production.test.js', 'potOddsLiveHeroCardResolver.production.test.js', 'potOddsCommunityBoardPlacement.production.test.js', 'potOddsPersistentPreflopUi.production.test.js', 'potOddsCanonicalBoardPersistentHandUi.production.test.js', 'potOddsStableVisibilityAndLiveDrag.production.test.js', 'potOddsUi.production.test.js'],
  statExplainability: ['statExplanation.test.js', 'statExplanation.production.test.js'],
  statEvidence: ['statEvidence.test.js'],
  handStatInspector: ['handStatInspector.test.js', 'handStatInspector.production.test.js', 'handInspectorScrollHudCoexistence.production.test.js'],
  playerProfileScoreInspector: ['playerProfileScoreInspector.test.js', 'playerProfileScoreInspector.production.test.js'],
  playerProfileExplainability: ['playerProfileExplanation.test.js', 'playerProfileExplainability.production.test.js', 'finalUiProfileClarity.test.js'],
  playerDashboard: ['playerDashboardGeometry.production.test.js', 'playerDashboardGeometry.browser.test.js', 'playerDashboardEvidence.test.js', 'careerPlayerProfile.test.js', 'careerPlayerProfile.production.test.js', 'playerDashboard.test.js', 'playerDashboard.production.test.js', 'playerDashboardPhase4C.test.js', 'playerDashboardPhase4C.production.test.js', 'playerDashboardPhase4C1.production.test.js', 'situationalDashboard.production.test.js', 'compactDashboardSettings.production.test.js', 'playerNotesStore.test.js', 'playerNotesCapacity.production.test.js', 'careerRelationalProvenance.test.js'],
  trackedPlayers: ['trackedPlayers.test.js', 'trackedPlayers.production.test.js'],
  playerProfiling: ['playerProfileClassifier.test.js', 'playerProfileClassifierCalibration.test.js', 'playerProfileSemanticCalibration.test.js', 'playerProfileTableContext.test.js', 'playerProfileTagCompatibilityCalibration.test.js', 'playerProfilePresentation.test.js', 'playerProfileLiveValidation.test.js', 'playerProfileLiveIdentity.production.test.js', 'playerProfileShadowStore.test.js', 'playerProfileCalibration.test.js', 'playerProfileHistoricalIdentity.test.js', 'playerProfileShadowIntegration.production.test.js', 'playerProfileDebugApi.production.test.js', 'playerProfileVisibleHud.production.test.js'],
  statisticsAndWalks: ['stats.test.js', 'coreStatsContinuity.production.test.js', 'statsWalk.test.js', 'walkProductionPath.test.js', 'walkSettlement.production.test.js', 'multiwayWalk.production.test.js', 'walkLifecycleContinuity.production.test.js', 'multiwayCBetOrdering.production.test.js', 'pokernow.e2e.test.js'],
  seatOverlays: ['overlayStats.test.js', 'overlayStats.production.test.js', 'seatOverlay.test.js', 'seatOverlayFormatting.production.test.js', 'hudLayoutLayering.production.test.js', 'hudPlaceholdersLayering.production.test.js', 'seatMapping.production.test.js', 'seatDomCleanup.production.test.js', 'overlayDrag.production.test.js', 'overlayGripLive.production.test.js', 'withheldPlaceholder.production.test.js', 'statTooltip.test.js', 'statTooltip.production.test.js'],
  seatHudUsabilityFinalization: ['seatHudCanonicalPositioning.test.js', 'seatHudSourceSwitch.production.test.js', 'seatHudLayeringFinalization.production.test.js', 'seatHudLedgerSuppression.production.test.js', 'seatHudVisualPanelDom.production.test.js', 'seatHudLivePanelBody.production.test.js'],
  runtimeAndPackaging: ['manifestScope.test.js', 'packageValidation.test.js', 'runtimeScope.test.js', 'runtimeScopeOrder.production.test.js', 'sameDocumentRouteTransition.production.test.js', 'websocketTransportOrdering.test.js', 'uiGuardAbort.production.test.js', 'optimizationMaintainability.test.js'],
  uiAndDisplayModes: ['displayModeSync.test.js', 'hudVisibilitySourceOfTruth.production.test.js', 'uiBootstrap.production.test.js', 'settingsUi.test.js', 'settingsUi.production.test.js', 'settingsPanelFix.production.test.js', 'leaderboardStats.test.js', 'leaderboardStats.production.test.js', 'leaderboardSource.production.test.js', 'sessionResetCareerIdentity.production.test.js', 'leaderboardHudPosition.test.js', 'leaderboardHudDrag.production.test.js', 'leaderboardHudReset.production.test.js', 'smallHudStatus.production.test.js', 'hudRuntimeStatus.test.js', 'hudRuntimeStatus.production.test.js', 'hudStatusMapping.production.test.js'],
  diagnostics: ['hudDiagnostics.test.js', 'hudHealth.test.js', 'handSourceTrace.production.test.js', 'gameBreakLifecycle.production.test.js', 'pauseLifecycleCapture.test.js', 'pauseDiagnosticCapture.test.js', 'pauseTransportHook.test.js', 'pauseDiagnosticStartup.production.test.js', 'pauseDiagnosticMarkerOwnership.test.js', 'pauseDiagnosticActivationWindow.test.js', 'showdownDiagnosticExporter.test.js', 'showdownDiagnosticExporter.production.test.js'],
  stabilizationBPerformance: ['sessionStatsCache.test.js', 'sessionPersistenceCadence.test.js', 'runtimeBounds.test.js', 'finalizationPerformanceEquivalence.test.js', 'careerDashboardOptimization.test.js', 'hudInvalidationPersistence.production.test.js', 'fullLogDiagnosticsGating.production.test.js', 'careerInitializationDecoupling.production.test.js', 'diagnosticDefaults.test.js', 'observerRenderBudget.production.test.js', 'stabilizationBPerformance.test.js', 'stabilizationBSoak.test.js'],
  suiteIntegrity: ['testSuites.test.js']
});

function unique(files) {
  return Array.from(new Set(files));
}

var fast = unique([
  'parser.test.js',
  'actionInference.test.js',
  'handFinalization.test.js',
  'semanticHandLedger.test.js',
  'semanticHandLedgerFixtures.production.test.js',
  'semanticHandLedgerLifecycle.production.test.js',
  'semanticHandLedgerShadowNeutrality.production.test.js',
  'preflopOpportunityReducer.test.js',
  'preflopMultiwayFoldToThreeBet.test.js',
  'preflopOpportunityReducerFixtures.production.test.js',
  'sanitizedCaptureDerivedPreflopFixtures.production.test.js',
  'preflopHudIntegration.production.test.js',
  'preflopHudContentPath.production.test.js',
  'preflopOpportunityReducerLifecycle.production.test.js',
  'preflopOpportunityReducerShadowNeutrality.production.test.js',
  'flopCBetOpportunityReducer.test.js',
  'flopCBetStatsIntegration.production.test.js',
  'flopCBetContentPath.production.test.js',
  'flopCBetVisibleIntegration.production.test.js',
  'showdownStatsReducer.test.js',
  'showdownUncontestedWinner.test.js',
  'showdownStatsContentPath.production.test.js',
  'showdownStatsAuthoritative.production.test.js',
  'showdownStatsVisibleIntegration.production.test.js',
  'showdownPostBreakLifecycle.production.test.js',
  'showdownFirstHandLifecycle.production.test.js',
  'careerStatsAggregator.test.js',
  'careerContributionStore.test.js',
  'careerStorageCapacity.test.js',
  'careerProductionPath.production.test.js',
  'careerBackup.test.js',
  'careerBackupCorruption.test.js',
  'careerBackupProductionPath.production.test.js',
  'careerBackupSeparation.production.test.js',
  'careerBackupPreflight.test.js',
  'careerBackupPreflight.production.test.js',
  'careerImport.test.js',
  'careerPortableFile.test.js',
  'careerDataSettings.test.js',
  'careerDataSettings.production.test.js',
  'careerSessionRemoval.test.js',
  'careerRelationalProvenance.test.js',
  'careerPlayerSummaries.test.js',
  'careerPlayerSummaryPerformance.test.js',
  'careerPlayerProfile.test.js',
  'careerPlayerProfile.production.test.js',
  'trackedPlayers.test.js',
  'trackedPlayers.production.test.js',
  'positionResolver.test.js',
  'positionProductionPath.production.test.js',
  'positionalAggregation.test.js',
  'filteredStats.test.js',
  'situationalDashboard.test.js',
  'situationalDashboard.production.test.js',
  'careerTrends.test.js',
  'careerTrendsService.test.js',
  'careerTrends.production.test.js',
  'careerTrendsPerformance.test.js',
  'selfIdentity.production.test.js',
  'potOdds.test.js',
  'potOddsPosition.test.js',
  'potOddsDraggablePosition.production.test.js',
  'boardCompanionLayout.test.js',
  'boardCompanionStableTableLocal.production.test.js',
  'boardCompanionDragLifecycleHardening.production.test.js',
  'boardCompanionLiveUxFinalization.production.test.js',
  'boardCompanionDiagnosticBridge.production.test.js',
  'boardCompanionPersistentPotOdds.production.test.js',
  'potOddsSemanticPath.production.test.js',
  'potOddsLiveStateReconcile.production.test.js',
  'potOddsDecisionRenderTrigger.production.test.js',
  'potOddsProductionVisibilityHardening.production.test.js',
  'potOddsLiveHeroCardResolver.production.test.js',
  'potOddsCommunityBoardPlacement.production.test.js',
  'potOddsPersistentPreflopUi.production.test.js',
  'potOddsCanonicalBoardPersistentHandUi.production.test.js',
  'potOddsStableVisibilityAndLiveDrag.production.test.js',
  'potOddsUi.production.test.js',
  'statExplanation.test.js',
  'statExplanation.production.test.js',
  'statEvidence.test.js',
  'handStatInspector.test.js',
  'handStatInspector.production.test.js',
  'handInspectorScrollHudCoexistence.production.test.js',
  'playerProfileScoreInspector.test.js',
  'playerProfileScoreInspector.production.test.js',
  'playerProfileExplanation.test.js',
  'playerProfileExplainability.production.test.js',
  'finalUiProfileClarity.test.js',
  'playerDashboard.test.js',
  'playerDashboard.production.test.js',
  'playerDashboardEvidence.test.js',
  'playerDashboardPhase4C.test.js',
  'playerDashboardPhase4C.production.test.js',
  'playerDashboardPhase4C1.production.test.js',
  'playerDashboardGeometry.production.test.js',
  'playerDashboardGeometry.browser.test.js',
  'careerRestoreFirstHand.production.test.js',
  'compactDashboardSettings.production.test.js',
  'playerNotesStore.test.js',
  'playerNotesCapacity.production.test.js',
  'sameDocumentRouteTransition.production.test.js',
  'websocketTransportOrdering.test.js',
  'playerProfileClassifier.test.js',
  'playerProfileClassifierCalibration.test.js',
  'playerProfileSemanticCalibration.test.js',
  'playerProfileTableContext.test.js',
  'playerProfileTagCompatibilityCalibration.test.js',
  'playerProfilePresentation.test.js',
  'playerProfileLiveValidation.test.js',
  'playerProfileLiveIdentity.production.test.js',
  'playerProfileShadowStore.test.js',
  'playerProfileCalibration.test.js',
  'playerProfileHistoricalIdentity.test.js',
  'playerProfileShadowIntegration.production.test.js',
  'playerProfileDebugApi.production.test.js',
  'playerProfileVisibleHud.production.test.js',
  'showdownDiagnosticExporter.test.js',
  'showdownDiagnosticExporter.production.test.js',
  'sessionStatsCache.test.js',
  'sessionPersistenceCadence.test.js',
  'runtimeBounds.test.js',
  'finalizationPerformanceEquivalence.test.js',
  'careerDashboardOptimization.test.js',
  'hudInvalidationPersistence.production.test.js',
  'fullLogDiagnosticsGating.production.test.js',
  'careerInitializationDecoupling.production.test.js',
  'diagnosticDefaults.test.js',
  'observerRenderBudget.production.test.js',
  'stabilizationBPerformance.test.js',
  'stabilizationBSoak.test.js',
  'firstHandStartup.production.test.js',
  'coldStartBoundary.production.test.js',
  'breakReloadRestart.production.test.js',
  'finalizedAf.production.test.js',
  'interruptedHandRecovery.test.js',
  'pausedLifecycleRecovery.production.test.js',
  'pokerNowLifecycleSignal.production.test.js',
  'ownedHandReloadContinuity.production.test.js',
  'pauseRuntimeStatus.production.test.js',
  'verifiedHostPauseResume.production.test.js',
  'sessionPauseIdleOracle.production.test.js',
  'stats.test.js',
  'coreStatsContinuity.production.test.js',
  'statsWalk.test.js',
  'walkProductionPath.test.js',
  'walkSettlement.production.test.js',
  'multiwayWalk.production.test.js',
  'walkLifecycleContinuity.production.test.js',
  'multiwayCBetOrdering.production.test.js',
  'overlayStats.test.js',
  'overlayStats.production.test.js',
  'seatOverlay.test.js',
  'seatOverlayFormatting.production.test.js',
  'seatDomCleanup.production.test.js',
  'hudLayoutLayering.production.test.js',
  'hudPlaceholdersLayering.production.test.js',
  'seatHudCanonicalPositioning.test.js',
  'seatHudLivePanelBody.production.test.js',
  'seatHudSourceSwitch.production.test.js',
  'seatHudLayeringFinalization.production.test.js',
  'seatHudLedgerSuppression.production.test.js',
  'overlayGripLive.production.test.js',
  'hudDiagnostics.test.js',
  'hudHealth.test.js',
  'handSourceTrace.production.test.js',
  'handLogVirtualization.production.test.js',
  'gameBreakLifecycle.production.test.js',
  'pauseLifecycleCapture.test.js',
  'pauseDiagnosticCapture.test.js',
  'pauseTransportHook.test.js',
  'pauseDiagnosticStartup.production.test.js',
  'pauseDiagnosticMarkerOwnership.test.js',
  'pauseDiagnosticActivationWindow.test.js',
  'settingsUi.test.js',
  'settingsUi.production.test.js',
  'settingsPanelFix.production.test.js',
  'hudVisibilitySourceOfTruth.production.test.js',
  'leaderboardStats.test.js',
  'leaderboardStats.production.test.js',
  'leaderboardSource.production.test.js',
  'sessionResetCareerIdentity.production.test.js',
  'leaderboardHudPosition.test.js',
  'leaderboardHudDrag.production.test.js',
  'leaderboardHudReset.production.test.js',
  'smallHudStatus.production.test.js',
  'hudRuntimeStatus.test.js',
  'hudRuntimeStatus.production.test.js',
  'hudStatusMapping.production.test.js',
  'statTooltip.test.js',
  'statTooltip.production.test.js',
  'optimizationMaintainability.test.js',
  'testSuites.test.js'
]);
var full = unique(Object.keys(categories).reduce(function (files, category) {
  return files.concat(categories[category]);
}, []));
var releaseFreeze = Object.freeze(['releaseMetadata.test.js']);

module.exports = Object.freeze({ categories: categories, fast: fast, full: full, release: releaseFreeze });
